package com.kai.casinox;
import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.content.*;import java.util.*;
public class MainActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(5,8,18));getWindow().setNavigationBarColor(Color.rgb(5,8,18));setContentView(new V(this));}
 static class V extends View{
  Paint p=new Paint(1); Random rng=new Random(); SharedPreferences sp; int credits,page=0; String msg="READY";
  int gold=Color.rgb(244,197,83),blue=Color.rgb(39,112,255),cyan=Color.rgb(50,207,255),white=Color.rgb(245,248,255),muted=Color.rgb(142,154,180),bg=Color.rgb(5,8,18),card=Color.rgb(14,20,38);
  RectF slot1=new RectF(),slot2=new RectF(),blackjack=new RectF(),roulette=new RectF(),baccarat=new RectF(),play=new RectF(),back=new RectF(),wallet=new RectF();
  V(Context c){super(c);setClickable(true);setFocusable(true);sp=c.getSharedPreferences("kai_casino_x",0);credits=sp.getInt("credits",10000);}
  float d(float x){return x*getResources().getDisplayMetrics().density;}
  void txt(Canvas c,String s,float x,float y,float z,int col,boolean bold){p.setColor(col);p.setTextSize(d(z));p.setTypeface(Typeface.create("sans",bold?1:0));c.drawText(s,x,y,p);}
  void ctr(Canvas c,String s,float x,float y,float z,int col,boolean bold){p.setTextSize(d(z));p.setTypeface(Typeface.create("sans",bold?1:0));p.setColor(col);c.drawText(s,x-p.measureText(s)/2,y,p);}
  void rr(Canvas c,RectF q,float rad,int col){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(q,d(rad),d(rad),p);}
  RectF R(float l,float t,float r,float b){return new RectF(d(l),d(t),r<0?getWidth()+d(r):d(r),d(b));}
  protected void onDraw(Canvas c){super.onDraw(c);c.drawColor(bg);header(c);if(page==0)home(c);else game(c);}
  void header(Canvas c){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setColor(gold);c.drawCircle(d(30),d(35),d(20),p);p.setStyle(Paint.Style.FILL);ctr(c,"K",d(30),d(43),22,white,true);txt(c,"KAI CASINO",d(58),d(34),17,white,true);txt(c,"X",d(160),d(34),17,gold,true);txt(c,"PREMIUM SOCIAL CLUB",d(58),d(50),7,muted,true);wallet=R(-118,16,-14,60);rr(c,wallet,13,card);txt(c,"KX CREDITS",getWidth()-d(105),d(33),7,muted,true);txt(c,String.format(Locale.US,"%,d",credits),getWidth()-d(105),d(52),14,gold,true);}
  void home(Canvas c){RectF hero=R(15,78,-15,208);rr(c,hero,24,Color.rgb(11,23,47));txt(c,"KAI ROYALE",d(30),d(107),9,cyan,true);txt(c,"THE NIGHT",d(30),d(139),26,white,true);txt(c,"IS YOURS.",d(30),d(169),26,gold,true);txt(c,"Premium casino-style entertainment",d(30),d(191),9,muted,false);ctr(c,"♛",getWidth()-d(70),d(151),34,gold,true);
   String[] tabs={"LOBBY","SLOTS","TABLE","LIVE","VIP"};float tw=(getWidth()-d(30))/5f;for(int i=0;i<5;i++)ctr(c,tabs[i],d(15)+tw*(i+.5f),d(238),8,i==0?gold:muted,true);
   txt(c,"FEATURED GAMES",d(18),d(278),12,white,true);slot1=R(15,292,190,413);slot2=new RectF(getWidth()/2+d(5),d(292),getWidth()-d(15),d(413));tile(c,slot1,"KX FORTUNE","SLOTS","777",gold);tile(c,slot2,"ROYAL RUSH","SLOTS","♛",cyan);
   txt(c,"TABLE GAMES",d(18),d(448),12,white,true);blackjack=R(15,462,-15,524);roulette=R(15,536,-15,598);baccarat=R(15,610,-15,672);small(c,blackjack,"BLACKJACK","21","CLASSIC TABLE");small(c,roulette,"ROULETTE","●","EUROPEAN 0–36");small(c,baccarat,"BACCARAT","B","PREMIUM TABLE");
   float ny=getHeight()-d(58);RectF nav=new RectF(d(10),ny,getWidth()-d(10),getHeight()-d(8));rr(c,nav,20,Color.rgb(10,16,31));String[] n={"HOME","GAMES","REWARDS","PROFILE"};for(int i=0;i<4;i++){float x=d(10)+(getWidth()-d(20))/4f*(i+.5f);ctr(c,i==0?"⌂":i==1?"♛":i==2?"◇":"◎",x,ny+d(20),15,i==0?gold:muted,true);ctr(c,n[i],x,ny+d(39),7,i==0?gold:muted,true);}}
  void tile(Canvas c,RectF q,String name,String tag,String mark,int col){rr(c,q,20,card);RectF art=new RectF(q.left+d(9),q.top+d(9),q.right-d(9),q.top+d(74));rr(c,art,15,Color.rgb(18,31,58));ctr(c,mark,q.centerX(),q.top+d(56),30,col,true);txt(c,tag,q.left+d(13),q.top+d(92),7,cyan,true);txt(c,name,q.left+d(13),q.top+d(111),12,white,true);}
  void small(Canvas c,RectF q,String name,String mark,String sub){rr(c,q,17,card);RectF icon=new RectF(q.left+d(9),q.top+d(9),q.left+d(59),q.bottom-d(9));rr(c,icon,13,Color.rgb(19,31,54));ctr(c,mark,q.left+d(34),q.top+d(39),19,gold,true);txt(c,name,q.left+d(72),q.top+d(27),14,white,true);txt(c,sub,q.left+d(72),q.top+d(45),8,muted,false);RectF go=new RectF(q.right-d(45),q.top+d(14),q.right-d(9),q.bottom-d(14));rr(c,go,11,blue);ctr(c,"›",go.centerX(),q.top+d(38),20,white,true);}
  void game(Canvas c){back=R(10,70,120,115);txt(c,"‹  BACK",d(18),d(96),11,cyan,true);String title=page==1?"BLACKJACK":page==2?"EUROPEAN ROULETTE":page==3?"KX FORTUNE SLOTS":"BACCARAT";txt(c,title,d(18),d(132),24,white,true);txt(c,"PREMIUM DEMO TABLE",d(18),d(152),8,gold,true);RectF table=R(15,175,-15,430);rr(c,table,25,card);ctr(c,page==1?"A♠   K♥":page==2?"0  •  17  •  32":page==3?"7   ♛   7":"PLAYER   BANKER",getWidth()/2,d(290),28,gold,true);ctr(c,msg,getWidth()/2,d(385),11,muted,true);play=R(18,455,-18,525);rr(c,play,18,blue);ctr(c,page==3?"SPIN • 100":"PLAY ROUND • 100",getWidth()/2,d(498),14,white,true);txt(c,"Virtual credits only • No cash value",d(18),d(558),9,muted,false);}
  void enter(int p){page=p;msg="READY";invalidate();}
  void round(){if(credits<100){msg="INSUFFICIENT CREDITS";invalidate();return;}credits-=100;int w=rng.nextInt(5);if(w==0){credits+=500;msg="BIG WIN • +400 NET";}else if(w==1){credits+=200;msg="WIN • +100 NET";}else msg="ROUND COMPLETE";sp.edit().putInt("credits",credits).apply();invalidate();}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){return true;}if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();if(page==0){if(slot1.contains(x,y)||slot2.contains(x,y))enter(3);else if(blackjack.contains(x,y))enter(1);else if(roulette.contains(x,y))enter(2);else if(baccarat.contains(x,y))enter(4);else if(wallet.contains(x,y)){credits=10000;sp.edit().putInt("credits",credits).apply();invalidate();}}else{if(back.contains(x,y))enter(0);else if(play.contains(x,y))round();}performClick();return true;}
  public boolean performClick(){super.performClick();return true;}
 }
}