package com.kai.casinox;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.content.*;import java.util.*;
public class MainActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(5,8,18));getWindow().setNavigationBarColor(Color.rgb(5,8,18));setContentView(new V(this));}
 static class V extends View{
  Paint p=new Paint(1); Random r=new Random(); SharedPreferences sp; int credits,page=0; float sy=0; int gold=Color.rgb(244,197,83),blue=Color.rgb(39,112,255),cyan=Color.rgb(50,207,255),white=Color.rgb(245,248,255),muted=Color.rgb(142,154,180),bg=Color.rgb(5,8,18),card=Color.rgb(14,20,38); String msg="READY";
  V(Context c){super(c);sp=c.getSharedPreferences("kai_casino_x",0);credits=sp.getInt("credits",10000);p.setTypeface(Typeface.DEFAULT);}
  float d(float x){return x*getResources().getDisplayMetrics().density;} void t(Canvas c,String s,float x,float y,float z,int col,boolean b){p.setColor(col);p.setTextSize(d(z));p.setTypeface(Typeface.create("sans",b?1:0));c.drawText(s,x,y,p);} void ct(Canvas c,String s,float x,float y,float z,int col,boolean b){p.setTextSize(d(z));p.setTypeface(Typeface.create("sans",b?1:0));p.setColor(col);c.drawText(s,x-p.measureText(s)/2,y,p);} void rr(Canvas c,float l,float y,float x,float b,float q,int col){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,y,x,b,d(q),d(q),p);} void line(Canvas c,float l,float y,float x,float b,int col){p.setColor(col);p.setStrokeWidth(d(1));c.drawLine(l,y,x,b,p);} int a(int c,int a){return Color.argb(a,Color.red(c),Color.green(c),Color.blue(c));}
  protected void onDraw(Canvas c){c.drawColor(bg);p.setShader(new RadialGradient(getWidth()*.75f,d(60),d(240),a(blue,55),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(getWidth()*.75f,d(60),d(240),p);p.setShader(null);if(page==0)home(c);else game(c);}
  void logo(Canvas c,float x,float y){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(2));p.setColor(gold);c.drawCircle(x,y,d(20),p);p.setStrokeWidth(d(5));p.setColor(blue);c.drawArc(x-d(14),y-d(14),x+d(14),y+d(14),-55,235,false,p);p.setStyle(Paint.Style.FILL);ct(c,"K",x,y+d(8),22,white,true);}
  void header(Canvas c){logo(c,d(29),d(35));t(c,"KAI CASINO",d(57),d(34),17,white,true);t(c,"X",d(160),d(34),17,gold,true);t(c,"PREMIUM SOCIAL CLUB",d(57),d(50),7,muted,true);rr(c,getWidth()-d(115),d(17),getWidth()-d(15),d(57),13,card);t(c,"KX CREDITS",getWidth()-d(103),d(33),7,muted,true);t(c,String.format("%,d",credits),getWidth()-d(103),d(51),14,gold,true);}
  void home(Canvas c){header(c);float y=d(78);
   rr(c,d(15),y,getWidth()-d(15),y+d(130),24,Color.rgb(11,23,47));t(c,"KAI ROYALE",d(30),y+d(29),9,cyan,true);t(c,"THE NIGHT",d(30),y+d(61),26,white,true);t(c,"IS YOURS.",d(30),y+d(91),26,gold,true);t(c,"Premium casino-style entertainment",d(30),y+d(113),9,muted,false);rr(c,getWidth()-d(105),y+d(25),getWidth()-d(35),y+d(95),35,a(gold,25));ct(c,"♛",getWidth()-d(70),y+d(73),33,gold,true);
   String[] tabs={"LOBBY","SLOTS","TABLE","LIVE","VIP"};float tw=(getWidth()-d(30))/5;for(int i=0;i<5;i++){ct(c,tabs[i],d(15)+tw*i+tw/2,y+d(160),8,i==0?gold:muted,true);if(i==0)line(c,d(15)+tw*i+d(12),y+d(169),d(15)+tw*(i+1)-d(12),y+d(169),gold);}
   t(c,"FEATURED GAMES",d(18),y+d(200),12,white,true);t(c,"View all  ›",getWidth()-d(80),y+d(200),9,cyan,true);
   tile(c,d(15),y+d(214),(getWidth()-d(40))/2,y+d(335),"KX FORTUNE","SLOTS","777",gold);tile(c,(getWidth()+d(10))/2,y+d(214),getWidth()-d(15),y+d(335),"ROYAL RUSH","SLOTS","♛",cyan);
   t(c,"TABLE GAMES",d(18),y+d(370),12,white,true);small(c,d(15),y+d(384),"BLACKJACK","21","CLASSIC TABLE");small(c,d(15),y+d(458),"ROULETTE","●","EUROPEAN 0–36");small(c,d(15),y+d(532),"BACCARAT","B","PREMIUM TABLE");
   nav(c);
  }
  void tile(Canvas c,float l,float y,float x,float b,String n,String tag,String mark,int col){rr(c,l,y,x,b,20,card);rr(c,l+d(9),y+d(9),x-d(9),y+d(74),15,Color.rgb(18,31,58));ct(c,mark,(l+x)/2,y+d(56),30,col,true);t(c,tag,l+d(13),y+d(92),7,cyan,true);t(c,n,l+d(13),y+d(111),12,white,true);}
  void small(Canvas c,float l,float y,String n,String mark,String sub){rr(c,l,y,getWidth()-d(15),y+d(62),17,card);rr(c,l+d(9),y+d(9),l+d(59),y+d(53),13,Color.rgb(19,31,54));ct(c,mark,l+d(34),y+d(39),19,gold,true);t(c,n,l+d(72),y+d(27),14,white,true);t(c,sub,l+d(72),y+d(45),8,muted,false);rr(c,getWidth()-d(54),y+d(14),getWidth()-d(24),y+d(48),11,blue);ct(c,"›",getWidth()-d(39),y+d(38),20,white,true);}
  void nav(Canvas c){float y=getHeight()-d(58);rr(c,d(10),y,getWidth()-d(10),getHeight()-d(8),20,Color.rgb(10,16,31));String[] n={"⌂\nHOME","♛\nGAMES","◇\nREWARDS","◎\nPROFILE"};for(int i=0;i<4;i++){float x=d(10)+(getWidth()-d(20))/4*(i+.5f);ct(c,n[i].substring(0,1),x,y+d(20),15,i==0?gold:muted,true);ct(c,n[i].substring(2),x,y+d(38),7,i==0?gold:muted,true);}}
  void game(Canvas c){header(c);t(c,"‹  BACK",d(18),d(90),10,cyan,true);t(c,page==1?"BLACKJACK":page==2?"EUROPEAN ROULETTE":page==3?"KX FORTUNE SLOTS":"BACCARAT",d(18),d(125),24,white,true);t(c,"PREMIUM DEMO TABLE",d(18),d(145),8,gold,true);rr(c,d(15),d(170),getWidth()-d(15),d(430),25,card);ct(c,page==1?"A♠   K♥":page==2?"0  •  17  •  32":page==3?"7   ♛   7":"PLAYER   BANKER",getWidth()/2,d(285),28,gold,true);ct(c,msg,getWidth()/2,d(380),11,muted,true);rr(c,d(18),d(455),getWidth()-d(18),d(515),18,blue);ct(c,page==3?"SPIN • 100":"PLAY ROUND • 100",getWidth()/2,d(493),13,white,true);t(c,"Virtual credits only • No cash value",d(18),d(548),9,muted,false);}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=1)return true;float x=e.getX(),y=e.getY();if(page==0){float b=d(78);if(y>b+d(214)&&y<b+d(335))page=x<getWidth()/2?3:3;else if(y>b+d(384)&&y<b+d(446))page=1;else if(y>b+d(458)&&y<b+d(520))page=2;else if(y>b+d(532)&&y<b+d(594))page=4;}else if(y<d(110))page=0;else if(y>d(440)&&y<d(530)){if(credits>=100){credits-=100;int win=r.nextInt(5);if(win==0){credits+=500;msg="WIN • +400 NET";}else if(win==1){credits+=200;msg="WIN • +100 NET";}else msg="ROUND COMPLETE";sp.edit().putInt("credits",credits).apply();}else msg="INSUFFICIENT CREDITS";}invalidate();return true;}
 }
}